### ISSUE TITLE
Initialization failling

### ISSUE THREAD

**Issue by ibakayoko** [dazoakley/fake-elasticache#3]
/usr/local/lib/ruby/2.3.0/resolv.rb:95:in `getaddress': no address for memcached (Resolv::ResolvError)
from /usr/local/lib/ruby/2.3.0/resolv.rb:45:in `getaddress'
from /usr/local/bin/fake-elasticache:9:in `parse'
from /usr/local/bin/fake-elasticache:79:in `opts'
from /usr/local/bin/fake-elasticache:72:in `run!'
from /usr/local/bin/fake-elasticache:84:in `<main>'
/usr/local/lib/ruby/2.3.0/resolv.rb:95:in `getaddress': no address for memcached (Resolv::ResolvError)
from /usr/local/lib/ruby/2.3.0/resolv.rb:45:in `getaddress'
from /usr/local/bin/fake-elasticache:9:in `parse'
from /usr/local/bin/fake-elasticache:79:in `opts'
from /usr/local/bin/fake-elasticache:72:in `run!'
from /usr/local/bin/fake-elasticache:84:in `<main>'

**Comment by ibakayoko** [comment]
I see this error in the container logs

/usr/local/lib/ruby/2.3.0/resolv.rb:95:in `getaddress': no address for memcached (Resolv::ResolvError)
from /usr/local/lib/ruby/2.3.0/resolv.rb:45:in `getaddress'
from /usr/local/bin/fake-elasticache:9:in `parse'
from /usr/local/bin/fake-elasticache:79:in `opts'
from /usr/local/bin/fake-elasticache:72:in `run!'
from /usr/local/bin/fake-elasticache:84:in `<main>'

**Comment by HoltMansfield** [comment]
Me too.
